include:
  - project: 'gitops-demo/infra/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    ARM_SUBSCRIPTION_ID:
      vault: infrastructure/azure/ARM_SUBSCRIPTION_ID@secret
      file: false
    ARM_CLIENT_ID:
      vault: infrastructure/azure/ARM_CLIENT_ID@secret
      file: false
    ARM_CLIENT_SECRET:
      vault: infrastructure/azure/ARM_CLIENT_SECRET@secret
      file: false
    ARM_TENANT_ID:
      vault: infrastructure/azure/ARM_TENANT_ID@secret
      file: false
    GITLAB_TOKEN:
      vault: infrastructure/gitlab/GITLAB_TOKEN@secret
      file: false
